version: '3.3'
services:
  db:
    image: library/postgres
    environment:
      POSTGRES_USER: app_user
      POSTGRES_PASSWORD: complex_password
      POSTGRES_DB: employees_db
    volumes:
      - ./postgresql/sql:/docker-entrypoint-initdb.d/
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always
    networks:
      - postgres-network

networks:
  postgres-network:
    driver: "bridge"

volumes:
  postgres_data:
    driver: local
